#!/bin/bash
## test home
testdir=$(cd $(dirname $0)/; pwd)
## word home
workdir=$(dirname $testdir)
cd $workdir

control=./control

cfg=./perfcounter.json
httpport=`cat perfcounter.json | grep -A3 "\"http\":" | grep "\"listen\"" | cut -d\" -f4 | cut -d: -f2`
httpprex="127.0.0.1:$httpport"

## pfc
function pfc(){
    args=$@
    for i in $@; do
        url="$url/$i"
    done
    echo $url
    curl -s "$httpprex$url" | python -m json.tool
}

## control
function control(){
    $control $@
}

action=$1
case $action in
    "proc")
        pfc "pfc" $@
        ;;
    "pfc")
        pfc $@
        ;;
    "")
        pfc "pfc/proc/metrics/gauge,counter,meter,histogram/json"
        ;;
    *)
        control $@
        ;;
esac

